// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcnhsyrtbqibtwyaihep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbmhzeXJ0YnFpYnR3eWFpaGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDIzOTgsImV4cCI6MjA3ODI3ODM5OH0.NJ9rBgxOIEZ_Tt5jQ3KpnNwmXPe_k8Fx0lIfmn9i3jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});